# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  batch: true
  branches:
    include:
      - Developer
    exclude:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: $(Build.SourceBranchName)$(Rev:.r)

steps:
  - task: oneLuckiDevJson2Variable@1
    inputs:
      jsonFile: '$(Build.SourcesDirectory)\XCBL.SoapWebService.Phase2\xCBLSoapWebService\version.json'
      shouldPrefixVariables: false
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $lastIndex = '$(Build.BuildNumber)'.LastIndexOf('.')
        Write-Host $env:version
        Write-Host '$(Build.BuildNumber)'.substring($lastIndex)
        $jsonVersion = $env:version + '$(Build.BuildNumber)'.substring($lastIndex)
        Write-Host $jsonVersion
        Write-Host "##vso[task.setvariable variable=version;]$jsonVersion"
  - task: BuildVersioning@0
    inputs:
      sourcePath: '$(build.SourcesDirectory)'
      versionSource: 'variable'
      customNumberVariable: 'version'
      paramAssemblyVersion: '4'
      paramAssemblyFileVersion: '4'
      paramAssemblyInformationalVersion: '4'
      paramOverwriteFourthDigitWithBuildCounter: false
      paramVersionCode: '2'
      doAssemblyInfoAppendSuffix: false
      doConvertAssemblyInfoToLowerCase: false
      buildNumberVersionFormat: '3'
      buildNumberAction: 'nothing'
      doReplaceAssemblyInfo: true
      filePatternAssemblyInfo: '**\AssemblyInfo.*'
      doReplaceNuspec: false
      doReplaceNpm: false
      doReplaceDotNetCore: false
      doReplaceAndroid: false
      doReplaceiOS: false
      doReplaceCustom: true
      filePatternCustom: '**\*.sqlproj'
      paramCustomSearchRegex: '(<DacVersion>)(\d+\.\d+\.\d+(?:\.\d+)?)(</DacVersion>)'
      paramCustomReplaceRegex: '$1$(version)$3'
      doShowWarningsForUnmatchedRegex: true
      excludeFilePattern: |
        !**/bin/**
        !**/obj/**
        !**/node_modules/**
        !**/packages/**

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(build.SourcesDirectory)\XCBL.SoapWebService.Phase2\xCBLSoapWebService.sln'
      msbuildArgs: '/p:outdir=$(Build.ArtifactStagingDirectory) /p:DeployOnBuild=true'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      clean: true
      msbuildArchitecture: 'x64'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\_PublishedWebsites'
      ArtifactName: 'Websites'
      publishLocation: 'Container'
  - task: DeleteFiles@1
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory\_PublishedWebsites'
      Contents: 'xCBLSoapWebService_Package'
